### ISSUE TITLE
'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by zHaytam** [cjhutto/vaderSentiment#47]
Hello,

I am trying to use vaderSentiment with Python 2.7.12 but it's giving me this error, line: https://github.com/cjhutto/vaderSentiment/blob/master/vaderSentiment/vaderSentiment.py#L212

Does vaderSentiment support python 2?
Thank you.

**Comment by cjhutto** [comment]
We migrated to Python 3 a little while ago, so there may be backwards compatibility issues with Python 2.  For your issue -- in Python 2, the open() function takes no encoding argument (the third argument is the buffering option instead).

The fix is to add the following line near the top of the vaderSentiment.py file:
`from io import open`

If you are able to make this work, let me know, and I'll update the master branch so that others will benefit from this backwards compatibility hack.

**Comment by zHaytam** [comment]
Hello, thank you for the fast reply.

Adding `from io import open` seems to fix the issue (tested on 2.7.12 and 3.6).
I ran mine using `f.read().decode('UTF-8')` because I didn't see your message in time, but your solution is better since it handles both versions.

Thank you!

**Comment by rxng** [comment]
@cjhutto I've added that but it still comes up with this:

File "/usr/local/lib/python2.7/dist-packages/vaderSentiment/vaderSentiment.py", line 212, in __init__
lexicon_full_filepath = os.path.join(os.path.dirname(_this_module_file_path_), lexicon_file)
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by christianoruge** [comment]
You saved my day! Including the line in my script did it! Thanks 👍
