### ISSUE TITLE
Negation interpretation is very poor

### ISSUE THREAD

**Issue by mxchinegod** [cjhutto/vaderSentiment#70]
I will be looking for a solution to this but right now, things like the following:

> no problems ever
> Everything has been smooth. No problems or complaints.
> No problem as of yet
> Doing just fine no problems
> All good. No complaints.
> No problem everything good
> Very satisfied. No bad experiences.

are all being categorized as ~60% negative or more.

and yet things like this:

> New website is HORRIBLE

Has 53% negativity. For capitalized descriptions like "HORRIBLE", I would have expected much more accurate results, it seems like the same logic that is overestimating the negativity of words like "no" and "problem" is totally ignoring less general words like "horrible". This is not good at all.

I bring this up not in hopes it would get fixed, I think it's fundamentally a problem with the approach this solution takes. I bring this up in case anyone was wondering if they should use this in a production scenario. You shouldn't. Especially not for customer support or CXM-related jobs. There is almost no common sense context awareness in VADER and worse, it misses on obvious adjectives which have little ironic or contradictory uses.

**Comment by cjhutto** [comment]
This is more of a misunderstanding / misinterpretation of the measured values being output by VADER.  As documented in the README, The `pos`, `neu`, and `neg` scores are **ratios** for the (weighted) proportions of text that fall in each of the three classes (positive, negative, or neutral). The class proportions are not (NOT!) assessed using all the sentence structure and word-order-sensitive rules, etc. (including the important _negations_ rules that would address the examples you identify)....rather, they represent something more akin to a bag-of-words (not sensitive to word-order situations where degree modifiers such as "really" or "very" might boost the valance, or how negation such as "not" or "no" will reverse the polarity); they are truly a simple proportional representation of number of class-relevant words relative to the total number of words in the sentence. (You might prefer to use the `compound` measure instead -- more on how it more robustly accounts for sentence level analytics below).

So, "New website is HORRIBLE" has a weighted negative proportion of 0.53.  Given that there are only three assessed words in this sentence (removing the stopword "is"), baseline/non-weighted proportions we might expect 0.33 negative (one negative word [horrible] out of three) and 0.67 neutral (two neutral words [new, website] out of three). 

But because horrible is capitalized, and because it's valence is moderately high (-2.5 valence in the lexicon [max possible negative valence for any lexical item would be -4]), the weighted proportion for the negative class for this sentence is increased from 0.33 to 0.53... I'd say VADER is doing a fine job for what it was built for...

But rather than trying to use (only) the proportional measures, many folks find that using the `compound` score can be very informative... The `compound` score handles word-order sensitive situations much better, as well as sentence-level understanding of text-based social communication conventions, linguistic heuristics, social jargon, etc. ... it considers all positive and negative valences against a host of sentiment-relevant conditionals, and then normalizes to a single value (continuous scale [-1, +1]).  For the examples, it would be better to split the samples into individual sentences and do the VADER analysis on each sentence... then do two class or three class binning the way it was done in the original publication 


        positive sentiment: compound score >= 0.05
        neutral sentiment: (compound score > -0.05) and (compound score < 0.05)
        negative sentiment: compound score <= -0.05

and compute class percentages for the overall review.

**Comment by mxchinegod** [comment]
> they are truly a simple proportional representation of number of class-relevant words relative to the total number of words in the sentence.

I would argue that this is not "sentiment analysis". Fundamentally, it's frequency analysis and key/value pairs assigned to vocabulary. 

I wonder if anyone sincerely built it this way with the assumption that this would accurately analyze sentiment. 

Akin to an alternate universe where word2vec says they are a vectorized language library, but it was just a fancy thesaurus. Thankfully that's not the case and it's a fantastic project but for how much people reference VADER as a "sentiment analysis" package, it seems rather misleading from an essential data science perspective. It's not sentiment analysis. It doesn't calculate sentiment. It just categorizes words and counts them with some normalization and boundaries.

**Comment by curtisdf** [comment]
I've been poring over the VADER algorithm this week, porting it to PHP and writing comprehensive tests.  I think some of the comments in this issue tracker are much too harsh.

Getting a computer to correctly parse the English language is HARD.  It has a voluminous vocabulary, many different nuances and forms, all sorts of slang and idioms, numerous ways that people fail to use correct grammar and punctuation in the first place, and the fact that the meanings of words change over time while new ones are always being created.  VADER has the best concept of anything else I've seen, despite some room for improvement.  Read the research paper.  It's only 10 pages, so it's not very long.  It's the best of anything out there, especially for the context is was written for, which is social media.

**Comment by cjhutto** [comment]
> It's not sentiment analysis. It doesn't calculate sentiment. It just categorizes words and counts them with some normalization and boundaries.

Shows a very shallow understanding of VADER sentiment analysis, imo. Perhaps I can help shed some light on the process under the hood for @DylanAlloy and others (since this is a common misunderstanding, especially among people who are used to other tools with measures that might be _called_ the same/similar, but don't _mean_ the same thing as VADER's measures for sentiment).

The measures you reference (proportional `pos`/`neu`/`neg`) are indeed frequency analysis of a bag-of-words model moderated by sentiment intensity valence awareness... a simplistic sentiment analysis, to be fair, but with it's own use cases. For example, research questions such as "what [weighted, relative] proportion of the text in this {speech, blog, paper, social media conversation, newspaper article, etc.} is positive versus negative versus neutral"?  Because we are operating on sub-sentence level text segments (e.g., the first part of the sentence might be weakly positive, and the second part strongly negative), it gets tricky (and sometimes not possible) to take advantage of the full sentence level analysis engine in VADER.  However...

For more of an "essential data science perspective" and those typical use cases, even a cursory reading of the accompanying publication and supporting material would indicate that the measure for `compound` sentiment is much a more robust sentiment analysis approach -- i.e., unit of analysis at the whole sentence level, with word order sensitivity, accounting for text-based human social communication conventions, linguistic heuristics, etc.  The difference is that the compound score reflects typical HUMAN cognitive processes _at the sentence level_ - e.g., when considering whether, on the whole, a given sentence is _overall_ more positive than negative (or vice versa), or neutral. Furthermore, a `compound ` score near 0 could indicate overall neutrality either (a) due to no sentiment laden content, or (b) due to content that is equally balanced in sentiment intensity for positive and negative polarities -- with the distinction between these two options being computationally determined using the proportional `pos`/`neu`/`neg` measures (another use case).

As such, VADER attempts to balance the tension/trade-off between being super accurate (but with limited general application) and being super generalizable (but less accurate).  Lot's of folks (myself included) have found VADER to be a handy "general purpose" sentiment analysis tool for social text (e.g., tweets, movie reviews, product reviews, forum comments, online news article comments) ... in 2016 researchers published a journal article in _EPJ Data Science_ that compared the state of the art (at that time) for 24 different publicly available sentiment analysis tools. [Table 8](https://epjdatascience.springeropen.com/articles/10.1140/epjds/s13688-016-0085-1/tables/8) in that paper shows that VADER was ranked highest (against 23 other tools) for versatility as determined by the best average ranking for 3-class F1-scores against 18 different data sets.

One of the ways VADER can be useful is as a semi-supervised bootstrap for highly-tailored sentiment reasoning on new data sets... train some ML models on new data by using VADER to initially label the text, since VADER does well in "general" sentiment analysis - then discover (new, domain-specific) concepts that also reflect sentiment.  Has worked well for developing especially tailored models for domain contexts such as political rhetoric, financial investment reports, company annual reports, corporate (project management) email communications, crowd sourced funding campaigns, quantifying bias in journalistic news articles, and others.  Also, can be quite useful to have VADER as one feature (among others, including other sentiment analysis tools) in an ensemble ML model.

**Comment by cjhutto** [comment]
Provided a fix for checking whether "no" is being used as negation for an adjacent lexicon item vs "no" as its own stand-alone lexicon item.

Output for samples now look like this:
```
Everything has been smooth. No problems or complaints.  
                                    {'neg': 0.0, 'neu': 0.571, 'pos': 0.429, 'compound': 0.5448}
no problems ever                    {'neg': 0.0, 'neu': 0.47, 'pos': 0.53, 'compound': 0.3089}
No problem as of yet                {'neg': 0.0, 'neu': 0.639, 'pos': 0.361, 'compound': 0.3089}
Doing just fine no problems         {'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.4692}
All good. No complaints.            {'neg': 0.0, 'neu': 0.279, 'pos': 0.721, 'compound': 0.6319}
No problem everything good          {'neg': 0.0, 'neu': 0.279, 'pos': 0.721, 'compound': 0.6319}
Very satisfied. No bad experiences. {'neg': 0.0, 'neu': 0.211, 'pos': 0.789, 'compound': 0.7569}
No problem.                         {'neg': 0.0, 'neu': 0.307, 'pos': 0.693, 'compound': 0.3089}
No complaints                       {'neg': 0.0, 'neu': 0.307, 'pos': 0.693, 'compound': 0.3089}
No worries.                         {'neg': 0.0, 'neu': 0.3, 'pos': 0.7, 'compound': 0.3252}
No good                             {'neg': 0.706, 'neu': 0.294, 'pos': 0.0, 'compound': -0.3412}
No smiles.                          {'neg': 0.719, 'neu': 0.281, 'pos': 0.0, 'compound': -0.3724}
No laughter.                        {'neg': 0.724, 'neu': 0.276, 'pos': 0.0, 'compound': -0.3875}
```

**Comment by cactuscode7** [comment]
Hi @cjhutto , Good job building VADER It works to  the level it was build for, referring to examples you've stated.. I think there is some contrary when I try to analyze the sentiment of  "No issues"...   
 -Thanks!
